# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_xbar_0/vga_xbar_0.xci
# IP: The module: 'vga_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_xbar_0/vga_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_xbar_0/vga_xbar_0.xci
# IP: The module: 'vga_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_xbar_0/vga_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
