# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/liulei/vga_mTwo/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_clk_wiz_1_0/vga_clk_wiz_1_0.xci
# IP: The module: 'vga_clk_wiz_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/liulei/vga_mTwo/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_clk_wiz_1_0/vga_clk_wiz_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/liulei/vga_mTwo/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_clk_wiz_1_0/vga_clk_wiz_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/liulei/vga_mTwo/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_clk_wiz_1_0/vga_clk_wiz_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/liulei/vga_mTwo/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_clk_wiz_1_0/vga_clk_wiz_1_0.xci
# IP: The module: 'vga_clk_wiz_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/liulei/vga_mTwo/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_clk_wiz_1_0/vga_clk_wiz_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/liulei/vga_mTwo/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_clk_wiz_1_0/vga_clk_wiz_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/liulei/vga_mTwo/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_clk_wiz_1_0/vga_clk_wiz_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
