# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/lin10/OneDrive/Desktop/ece532/vga_microblaze_0313/vga_microblaze_0313/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_axi_vdma_0_0/vga_axi_vdma_0_0.xci
# IP: The module: 'vga_axi_vdma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/lin10/OneDrive/Desktop/ece532/vga_microblaze_0313/vga_microblaze_0313/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_axi_vdma_0_0/vga_axi_vdma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_axi_vdma_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/lin10/OneDrive/Desktop/ece532/vga_microblaze_0313/vga_microblaze_0313/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_axi_vdma_0_0/vga_axi_vdma_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_axi_vdma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/lin10/OneDrive/Desktop/ece532/vga_microblaze_0313/vga_microblaze_0313/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_axi_vdma_0_0/vga_axi_vdma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_axi_vdma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/lin10/OneDrive/Desktop/ece532/vga_microblaze_0313/vga_microblaze_0313/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_axi_vdma_0_0/vga_axi_vdma_0_0.xci
# IP: The module: 'vga_axi_vdma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/lin10/OneDrive/Desktop/ece532/vga_microblaze_0313/vga_microblaze_0313/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_axi_vdma_0_0/vga_axi_vdma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_axi_vdma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/lin10/OneDrive/Desktop/ece532/vga_microblaze_0313/vga_microblaze_0313/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_axi_vdma_0_0/vga_axi_vdma_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_axi_vdma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/lin10/OneDrive/Desktop/ece532/vga_microblaze_0313/vga_microblaze_0313/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_axi_vdma_0_0/vga_axi_vdma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_axi_vdma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
