# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/vga_microblaze.xdc

# Block Designs: bd/vga/vga.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vga || ORIG_REF_NAME==vga} -quiet] -quiet

# IP: bd/vga/ip/vga_v_tc_0_0/vga_v_tc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vga_v_tc_0_0 || ORIG_REF_NAME==vga_v_tc_0_0} -quiet] -quiet

# IP: bd/vga/ip/vga_v_axi4s_vid_out_0_0/vga_v_axi4s_vid_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vga_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==vga_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/vga/ip/vga_xlslice_0_0/vga_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vga_xlslice_0_0 || ORIG_REF_NAME==vga_xlslice_0_0} -quiet] -quiet

# IP: bd/vga/ip/vga_axi_vdma_0_0/vga_axi_vdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vga_axi_vdma_0_0 || ORIG_REF_NAME==vga_axi_vdma_0_0} -quiet] -quiet

# IP: bd/vga/ip/vga_rgb2vga_0_0/vga_rgb2vga_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vga_rgb2vga_0_0 || ORIG_REF_NAME==vga_rgb2vga_0_0} -quiet] -quiet

# IP: bd/vga/ip/vga_axi_dynclk_0_0/vga_axi_dynclk_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vga_axi_dynclk_0_0 || ORIG_REF_NAME==vga_axi_dynclk_0_0} -quiet] -quiet

# IP: bd/vga/ip/vga_microblaze_0_0/vga_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vga_microblaze_0_0 || ORIG_REF_NAME==vga_microblaze_0_0} -quiet] -quiet

# IP: bd/vga/ip/vga_dlmb_v10_0/vga_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vga_dlmb_v10_0 || ORIG_REF_NAME==vga_dlmb_v10_0} -quiet] -quiet

# IP: bd/vga/ip/vga_ilmb_v10_0/vga_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vga_ilmb_v10_0 || ORIG_REF_NAME==vga_ilmb_v10_0} -quiet] -quiet

# IP: bd/vga/ip/vga_dlmb_bram_if_cntlr_0/vga_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vga_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==vga_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/vga/ip/vga_ilmb_bram_if_cntlr_0/vga_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vga_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==vga_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/vga/ip/vga_lmb_bram_0/vga_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vga_lmb_bram_0 || ORIG_REF_NAME==vga_lmb_bram_0} -quiet] -quiet

# IP: bd/vga/ip/vga_mdm_1_0/vga_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vga_mdm_1_0 || ORIG_REF_NAME==vga_mdm_1_0} -quiet] -quiet

# IP: bd/vga/ip/vga_clk_wiz_1_0/vga_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vga_clk_wiz_1_0 || ORIG_REF_NAME==vga_clk_wiz_1_0} -quiet] -quiet

# IP: bd/vga/ip/vga_rst_clk_wiz_1_100M_0/vga_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vga_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==vga_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/vga/ip/vga_rst_mig_7series_0_81M_0/vga_rst_mig_7series_0_81M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vga_rst_mig_7series_0_81M_0 || ORIG_REF_NAME==vga_rst_mig_7series_0_81M_0} -quiet] -quiet

# IP: bd/vga/ip/vga_xbar_0/vga_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vga_xbar_0 || ORIG_REF_NAME==vga_xbar_0} -quiet] -quiet

# IP: bd/vga/ip/vga_microblaze_0_axi_periph_0/vga_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vga_microblaze_0_axi_periph_0 || ORIG_REF_NAME==vga_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/vga/ip/vga_smartconnect_0_0/vga_smartconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vga_smartconnect_0_0 || ORIG_REF_NAME==vga_smartconnect_0_0} -quiet] -quiet

# IP: bd/vga/ip/vga_mig_7series_0_1/vga_mig_7series_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vga_mig_7series_0_1 || ORIG_REF_NAME==vga_mig_7series_0_1} -quiet] -quiet

# XDC: bd/vga/vga_ooc.xdc
