# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.cache/wt [current_project]
set_property parent.project_path D:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
set_property ip_repo_paths {
  d:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/rgb2vga_v1_0
  d:/Keyboard_gpio
  d:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/axi_dynclk
  d:/Pengj/Downloads/Pmods/PmodAD1_v1_0
  d:/vga_button/button_ip
  d:/0307
  d:/liulei/vga_microblaze_0301
  d:/liulei/vga_microblaze_0322/vga_microblaze
} [current_project]
update_ip_catalog
set_property ip_output_repo d:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib D:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/hdl/vga_wrapper.v
add_files D:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/vga.bd
set_property used_in_implementation false [get_files -all d:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_v_tc_0_0/vga_v_tc_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_v_tc_0_0/vga_v_tc_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_v_axi4s_vid_out_0_0/vga_v_axi4s_vid_out_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_v_axi4s_vid_out_0_0/vga_v_axi4s_vid_out_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_axi_vdma_0_0/vga_axi_vdma_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_axi_vdma_0_0/vga_axi_vdma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_axi_vdma_0_0/vga_axi_vdma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_axi_dynclk_0_0/src/axi_dynclk.xdc]
set_property used_in_implementation false [get_files -all d:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_microblaze_0_0/vga_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_microblaze_0_0/vga_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all d:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_microblaze_0_0/vga_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_dlmb_v10_0/vga_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all d:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_dlmb_v10_0/vga_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_ilmb_v10_0/vga_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all d:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_ilmb_v10_0/vga_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_dlmb_bram_if_cntlr_0/vga_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_ilmb_bram_if_cntlr_0/vga_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_lmb_bram_0/vga_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_mdm_1_0/vga_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all d:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_mdm_1_0/vga_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all d:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_clk_wiz_1_0/vga_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_clk_wiz_1_0/vga_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all d:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_clk_wiz_1_0/vga_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_rst_clk_wiz_1_100M_0/vga_rst_clk_wiz_1_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_rst_clk_wiz_1_100M_0/vga_rst_clk_wiz_1_100M_0.xdc]
set_property used_in_implementation false [get_files -all d:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_rst_clk_wiz_1_100M_0/vga_rst_clk_wiz_1_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_rst_mig_7series_0_81M_0/vga_rst_mig_7series_0_81M_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_rst_mig_7series_0_81M_0/vga_rst_mig_7series_0_81M_0.xdc]
set_property used_in_implementation false [get_files -all d:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_rst_mig_7series_0_81M_0/vga_rst_mig_7series_0_81M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_xbar_0/vga_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_mig_7series_0_1/vga_mig_7series_0_1/user_design/constraints/vga_mig_7series_0_1.xdc]
set_property used_in_implementation false [get_files -all d:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_mig_7series_0_1/vga_mig_7series_0_1/user_design/constraints/vga_mig_7series_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_xbar_1/vga_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_axi_intc_0_0/vga_axi_intc_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_axi_intc_0_0/vga_axi_intc_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_axi_intc_0_0/vga_axi_intc_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_axi_uartlite_0_0/vga_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_axi_uartlite_0_0/vga_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_axi_uartlite_0_0/vga_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_axi_gpio_0_0/vga_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_axi_gpio_0_0/vga_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_axi_gpio_0_0/vga_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_axi_gpio_0_1/vga_axi_gpio_0_1_board.xdc]
set_property used_in_implementation false [get_files -all d:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_axi_gpio_0_1/vga_axi_gpio_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_axi_gpio_0_1/vga_axi_gpio_0_1.xdc]
set_property used_in_implementation false [get_files -all d:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_blk_mem_gen_0_0/vga_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_axi_bram_ctrl_0_0/vga_axi_bram_ctrl_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_axi_gpio_1_0/vga_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_axi_gpio_1_0/vga_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_axi_gpio_1_0/vga_axi_gpio_1_0.xdc]
set_property used_in_implementation false [get_files -all d:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_auto_pc_0/vga_auto_pc_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all d:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_auto_us_0/vga_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_auto_us_0/vga_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_auto_us_0/vga_auto_us_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all d:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_auto_us_1/vga_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_auto_us_1/vga_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_auto_us_1/vga_auto_us_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all d:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_auto_cc_0/vga_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_auto_cc_0/vga_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_auto_cc_0/vga_auto_cc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/vga_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.srcs/constrs_1/new/vga_microblaze.xdc
set_property used_in_implementation false [get_files D:/liulei/vga_microblaze_0322/vga_microblaze/vga_microblaze.srcs/constrs_1/new/vga_microblaze.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top vga_wrapper -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef vga_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file vga_wrapper_utilization_synth.rpt -pb vga_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
