# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_v_axi4s_vid_out_0_0/vga_v_axi4s_vid_out_0_0.xci
# IP: The module: 'vga_v_axi4s_vid_out_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_v_axi4s_vid_out_0_0/vga_v_axi4s_vid_out_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_v_axi4s_vid_out_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_v_axi4s_vid_out_0_0/vga_v_axi4s_vid_out_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_v_axi4s_vid_out_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_v_axi4s_vid_out_0_0/vga_v_axi4s_vid_out_0_0.xci
# IP: The module: 'vga_v_axi4s_vid_out_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_v_axi4s_vid_out_0_0/vga_v_axi4s_vid_out_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_v_axi4s_vid_out_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_v_axi4s_vid_out_0_0/vga_v_axi4s_vid_out_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_v_axi4s_vid_out_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
