# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/vga_smartconnect_0_0.xci
# IP: The module: 'vga_smartconnect_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/bd_1608.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_0/bd_1608_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_1/bd_1608_psr0_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_2/bd_1608_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_3/bd_1608_psr_aclk1_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_4/bd_1608_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_5/bd_1608_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_6/bd_1608_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_7/bd_1608_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_8/bd_1608_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_9/bd_1608_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_10/bd_1608_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_11/bd_1608_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_12/bd_1608_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_13/bd_1608_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_14/bd_1608_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_15/bd_1608_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_16/bd_1608_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_17/bd_1608_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_18/bd_1608_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_19/bd_1608_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_20/bd_1608_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_21/bd_1608_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_22/bd_1608_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_23/bd_1608_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_24/bd_1608_s02mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_25/bd_1608_s02tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_26/bd_1608_s02sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_27/bd_1608_s02a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_28/bd_1608_sarn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_29/bd_1608_srn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_30/bd_1608_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_31/bd_1608_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_32/bd_1608_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_33/bd_1608_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_34/bd_1608_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_35/bd_1608_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_36/bd_1608_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_1/bd_1608_psr0_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_1/bd_1608_psr0_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_2/bd_1608_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_2/bd_1608_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_3/bd_1608_psr_aclk1_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_3/bd_1608_psr_aclk1_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_4/bd_1608_arsw_0_ooc.xdc

# XDC: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_5/bd_1608_rsw_0_ooc.xdc

# XDC: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_6/bd_1608_awsw_0_ooc.xdc

# XDC: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_7/bd_1608_wsw_0_ooc.xdc

# XDC: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_8/bd_1608_bsw_0_ooc.xdc

# XDC: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_12/bd_1608_s00a2s_0_ooc.xdc

# XDC: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_13/bd_1608_sarn_0_ooc.xdc

# XDC: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_14/bd_1608_srn_0_ooc.xdc

# XDC: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_15/bd_1608_sawn_0_ooc.xdc

# XDC: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_16/bd_1608_swn_0_ooc.xdc

# XDC: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_17/bd_1608_sbn_0_ooc.xdc

# XDC: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_21/bd_1608_s01a2s_0_ooc.xdc

# XDC: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_22/bd_1608_sarn_1_ooc.xdc

# XDC: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_23/bd_1608_srn_1_ooc.xdc

# XDC: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_27/bd_1608_s02a2s_0_ooc.xdc

# XDC: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_28/bd_1608_sarn_2_ooc.xdc

# XDC: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_29/bd_1608_srn_2_ooc.xdc

# XDC: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_30/bd_1608_m00s2a_0_ooc.xdc

# XDC: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_31/bd_1608_m00arn_0_ooc.xdc

# XDC: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_32/bd_1608_m00rn_0_ooc.xdc

# XDC: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_33/bd_1608_m00awn_0_ooc.xdc

# XDC: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_34/bd_1608_m00wn_0_ooc.xdc

# XDC: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_35/bd_1608_m00bn_0_ooc.xdc

# XDC: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_smartconnect_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/vga_smartconnect_0_0.xci
# IP: The module: 'vga_smartconnect_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/bd_1608.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_0/bd_1608_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_1/bd_1608_psr0_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_2/bd_1608_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_3/bd_1608_psr_aclk1_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_4/bd_1608_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_5/bd_1608_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_6/bd_1608_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_7/bd_1608_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_8/bd_1608_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_9/bd_1608_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_10/bd_1608_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_11/bd_1608_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_12/bd_1608_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_13/bd_1608_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_14/bd_1608_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_15/bd_1608_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_16/bd_1608_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_17/bd_1608_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_18/bd_1608_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_19/bd_1608_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_20/bd_1608_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_21/bd_1608_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_22/bd_1608_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_23/bd_1608_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_24/bd_1608_s02mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_25/bd_1608_s02tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_26/bd_1608_s02sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_27/bd_1608_s02a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_28/bd_1608_sarn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_29/bd_1608_srn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_30/bd_1608_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_31/bd_1608_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_32/bd_1608_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_33/bd_1608_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_34/bd_1608_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_35/bd_1608_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_36/bd_1608_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_1/bd_1608_psr0_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_1/bd_1608_psr0_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_2/bd_1608_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_2/bd_1608_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_3/bd_1608_psr_aclk1_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_3/bd_1608_psr_aclk1_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_4/bd_1608_arsw_0_ooc.xdc

# XDC: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_5/bd_1608_rsw_0_ooc.xdc

# XDC: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_6/bd_1608_awsw_0_ooc.xdc

# XDC: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_7/bd_1608_wsw_0_ooc.xdc

# XDC: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_8/bd_1608_bsw_0_ooc.xdc

# XDC: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_12/bd_1608_s00a2s_0_ooc.xdc

# XDC: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_13/bd_1608_sarn_0_ooc.xdc

# XDC: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_14/bd_1608_srn_0_ooc.xdc

# XDC: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_15/bd_1608_sawn_0_ooc.xdc

# XDC: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_16/bd_1608_swn_0_ooc.xdc

# XDC: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_17/bd_1608_sbn_0_ooc.xdc

# XDC: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_21/bd_1608_s01a2s_0_ooc.xdc

# XDC: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_22/bd_1608_sarn_1_ooc.xdc

# XDC: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_23/bd_1608_srn_1_ooc.xdc

# XDC: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_27/bd_1608_s02a2s_0_ooc.xdc

# XDC: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_28/bd_1608_sarn_2_ooc.xdc

# XDC: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_29/bd_1608_srn_2_ooc.xdc

# XDC: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_30/bd_1608_m00s2a_0_ooc.xdc

# XDC: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_31/bd_1608_m00arn_0_ooc.xdc

# XDC: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_32/bd_1608_m00rn_0_ooc.xdc

# XDC: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_33/bd_1608_m00awn_0_ooc.xdc

# XDC: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_34/bd_1608_m00wn_0_ooc.xdc

# XDC: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/bd_0/ip/ip_35/bd_1608_m00bn_0_ooc.xdc

# XDC: d:/liulei/vga_microblaze/vga_microblaze/vga_microblaze.srcs/sources_1/bd/vga/ip/vga_smartconnect_0_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_smartconnect_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
